import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { CLIPTokenizer } from '../src/native/tokenizer';

// The BPE merges are a bundled native asset (gitignored, regenerated by
// tools/model-conversion/build_assets.sh) rather than checked into the repo —
// skip gracefully rather than fail when it hasn't been generated locally.
const mergesPath = join(
  __dirname,
  '../android/app/src/main/assets/bpe_merges.txt',
);
const describeIfAssetPresent = existsSync(mergesPath) ? describe : describe.skip;

// Verified against the Python open_clip reference tokenizer — see
// tools/tok_test.ts, which this test supersedes as the wired-in check.
const EXPECTED: Record<string, number[]> = {
  dog: [49406, 1929, 49407],
  'a photo of a dog': [49406, 320, 1125, 539, 320, 1929, 49407],
  'sunset over the beach': [49406, 3424, 962, 518, 2117, 49407],
  'Hello World 123': [49406, 3306, 1002, 272, 273, 274, 49407],
  'a cat & a dog': [49406, 320, 2368, 261, 320, 1929, 49407],
};

describeIfAssetPresent('CLIPTokenizer', () => {
  const tokenizer = new CLIPTokenizer(readFileSync(mergesPath, 'utf-8'));

  it.each(Object.entries(EXPECTED))('tokenizes %j to match the Python reference', (text, expected) => {
    const ids = tokenizer.tokenize(text).filter((v, i) => i === 0 || v !== 0); // drop padding
    expect(ids.slice(0, expected.length)).toEqual(expected);
  });

  it('always wraps output with start/end-of-text tokens', () => {
    const ids = tokenizer.tokenize('anything');
    expect(ids[0]).toBe(49406);
    expect(ids.filter(v => v !== 0).at(-1)).toBe(49407);
  });

  it('pads to the fixed 77-token context length', () => {
    expect(tokenizer.tokenize('short query')).toHaveLength(77);
  });

  it('truncates long input but keeps the end-of-text token', () => {
    const longText = new Array(200).fill('word').join(' ');
    const ids = tokenizer.tokenize(longText);
    expect(ids).toHaveLength(77);
    expect(ids.at(-1)).toBe(49407);
  });
});
